# Generated by Django 2.1.8 on 2019-08-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btext', models.TextField(verbose_name='患者留言')),
                ('breply', models.TextField(blank=True, null=True, verbose_name='医生回复')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '留言板',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, verbose_name='县/区')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '县/市',
            },
        ),
        migrations.CreateModel(
            name='DetailSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsname', models.CharField(max_length=20, verbose_name='详细科名')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '详细疾病种类',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20, verbose_name='用户名')),
                ('dpasswd', models.CharField(max_length=150, verbose_name='密码')),
                ('dgender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('dbirth', models.DateField(verbose_name='出生日期')),
                ('dlevel', models.CharField(choices=[('1', '医师'), ('2', '主治医师'), ('3', '副主任医师'), ('4', '主任医师')], default='医师', max_length=32, verbose_name='级别')),
                ('dphoto', models.ImageField(max_length=150, upload_to='static/img', verbose_name='照片')),
                ('dtel', models.CharField(max_length=11, unique=True, verbose_name='电话')),
                ('demail', models.CharField(max_length=20, unique=True, verbose_name='邮箱')),
                ('dtext', models.TextField(max_length=5000, verbose_name='医生介绍')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '医生信息',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20, verbose_name='医院名')),
                ('hlevel', models.CharField(choices=[('1', '三级甲等'), ('2', '三级乙等'), ('3', '三级丙等'), ('4', '二级甲等'), ('5', '二级乙等'), ('6', '二级丙等'), ('7', '一级甲等'), ('8', '一级乙等'), ('9', '一级丙等')], default='三级甲等', max_length=20, verbose_name='等级')),
                ('hphoto', models.ImageField(max_length=150, upload_to='static/img', verbose_name='医院照片')),
                ('htel', models.CharField(max_length=20, unique=True, verbose_name='电话')),
                ('haddress', models.CharField(max_length=50, verbose_name='医院地址')),
                ('htext', models.TextField(max_length=5000, verbose_name='医院介绍')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Country')),
            ],
            options={
                'verbose_name_plural': '医院信息',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20, verbose_name='疾病名')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('dsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.DetailSubject')),
            ],
            options={
                'verbose_name_plural': '疾病信息',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=20, verbose_name='日期')),
                ('mprice', models.CharField(max_length=5, verbose_name='挂号价格')),
                ('muid1', models.IntegerField(blank=True, null=True, verbose_name='挂号用户1')),
                ('mpay1', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户1状态')),
                ('muid2', models.IntegerField(blank=True, null=True, verbose_name='挂号用户2')),
                ('mpay2', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户2状态')),
                ('muid3', models.IntegerField(blank=True, null=True, verbose_name='挂号用户3')),
                ('mpay3', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户3状态')),
                ('muid4', models.IntegerField(blank=True, null=True, verbose_name='挂号用户4')),
                ('mpay4', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户4状态')),
                ('muid5', models.IntegerField(blank=True, null=True, verbose_name='挂号用户5')),
                ('mpay5', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户5状态')),
                ('muid6', models.IntegerField(blank=True, null=True, verbose_name='挂号用户6')),
                ('mpay6', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户6状态')),
                ('muid7', models.IntegerField(blank=True, null=True, verbose_name='挂号用户7')),
                ('mpay7', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户7状态')),
                ('muid8', models.IntegerField(blank=True, null=True, verbose_name='挂号用户8')),
                ('mpay8', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户8状态')),
                ('muid9', models.IntegerField(blank=True, null=True, verbose_name='挂号用户9')),
                ('mpay9', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户9状态')),
                ('muid10', models.IntegerField(blank=True, null=True, verbose_name='挂号用户10')),
                ('mpay10', models.CharField(choices=[('0', '无人预约'), ('1', '未支付'), ('2', '已支付')], default='0', max_length=32, verbose_name='用户10状态')),
                ('mnumber', models.CharField(default=0, max_length=10, verbose_name='已挂号人数')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '预约挂号信息',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=50, verbose_name='标题')),
                ('ntext', models.TextField(max_length=5000, verbose_name='内容')),
                ('nphoto', models.ImageField(upload_to='static/img', verbose_name='配图')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('nhospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Hospital')),
            ],
            options={
                'verbose_name_plural': '公告信息',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20, verbose_name='科室名')),
                ('rtext', models.TextField(max_length=5000, verbose_name='科室介绍')),
                ('rtel', models.CharField(max_length=20, unique=True, verbose_name='电话')),
                ('mon1', models.CharField(blank=True, max_length=20, null=True, verbose_name='周一上午')),
                ('mon2', models.CharField(blank=True, max_length=20, null=True, verbose_name='周一下午')),
                ('tue1', models.CharField(blank=True, max_length=20, null=True, verbose_name='周二上午')),
                ('tue2', models.CharField(blank=True, max_length=20, null=True, verbose_name='周二下午')),
                ('wed1', models.CharField(blank=True, max_length=20, null=True, verbose_name='周三上午')),
                ('wed2', models.CharField(blank=True, max_length=20, null=True, verbose_name='周三下午')),
                ('thu1', models.CharField(blank=True, max_length=20, null=True, verbose_name='周四上午')),
                ('thu2', models.CharField(blank=True, max_length=20, null=True, verbose_name='周四下午')),
                ('fri1', models.CharField(blank=True, max_length=20, null=True, verbose_name='周五上午')),
                ('fri2', models.CharField(blank=True, max_length=20, null=True, verbose_name='周五下午')),
                ('sat1', models.CharField(blank=True, max_length=20, null=True, verbose_name='周六上午')),
                ('sat2', models.CharField(blank=True, max_length=20, null=True, verbose_name='周六下午')),
                ('sun1', models.CharField(blank=True, max_length=20, null=True, verbose_name='周日上午')),
                ('sun2', models.CharField(blank=True, max_length=20, null=True, verbose_name='周日下午')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('dsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.DetailSubject')),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Hospital')),
            ],
            options={
                'verbose_name_plural': '科室信息',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='科名')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '疾病种类',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('upasswd', models.CharField(max_length=150, verbose_name='密码')),
                ('ugender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('ubirth', models.CharField(max_length=20, verbose_name='出生日期')),
                ('uaddress', models.CharField(max_length=20, verbose_name='地址')),
                ('utel', models.CharField(max_length=11, unique=True, verbose_name='电话')),
                ('uemail', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Room'),
        ),
        migrations.AddField(
            model_name='illness',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Subject'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Room'),
        ),
        migrations.AddField(
            model_name='detailsubject',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Subject'),
        ),
        migrations.AddField(
            model_name='board',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Doctor'),
        ),
        migrations.AddField(
            model_name='board',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.User'),
        ),
    ]
